# Generated by Django 3.0.8 on 2020-09-20 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal23', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventname',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='null'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 16, 16, 19, 894096), verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.CharField(default='m', max_length=60),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='null', max_length=50, verbose_name='Event Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
