# Generated by Django 3.0.8 on 2020-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal23', '0002_auto_20200920_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default='null', verbose_name='Event Date'),
        ),
    ]
