# Generated by Django 3.0.8 on 2020-09-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal23', '0003_auto_20200920_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default='yyyy-mm-dd', verbose_name='Event Date'),
        ),
    ]
