# Generated by Django 3.0.8 on 2020-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal23', '0004_auto_20200920_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default='', verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default=False, max_length=50, verbose_name='Event Name'),
        ),
    ]
