# Generated by Django 3.0.8 on 2020-09-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0002_auto_20200928_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='LastName',
            new_name='lastName',
        ),
    ]
